### ISSUE TITLE
[Bug]: JTE doesn't downloaded configurations for PR

### ISSUE THREAD

**Issue by kamorozov** [jenkinsci/templating-engine-plugin#265]
### Jenkins Version

Jenkins 2.289.3

### JTE Version

2.0.3

### Bug Description

Hi!

We use JTE with Bitbucket plugin (Bitbucket Team/Project pipeline). Everything works well for branches, but JTE doesn't get libraries and any configs from application repositories for PR.

### Relevant log output

```shell
For example
1) For feature branch

[JTE] Obtained Pipeline Configuration File (show)
[JTE] Pipeline Configuration Modifications (show)
[JTE] Obtained Template Configuration File (show)
[JTE] Pipeline Configuration Modifications (show)
[JTE] Loading Library artifactory (show)
[JTE] Loading Library branch (show)
[JTE] Loading Library jenkins (show)
[JTE] Loading Library scm (show)
[JTE] Loading Library fabric (show)
[JTE] Loading Library gradle (show)
[JTE] Template Primitives are overwriting Jenkins steps with the following names: (show)
[JTE] Obtained Repository Jenkinsfile (show)
[JTE] -- scm: git ssh://git@stash.gto.intranet.db.com:7999/ESP_TOOLS/espear-2.0-srm-uk-outbound-crest-publisher.git
[JTE] -- file path: Jenkinsfile
[JTE] Obtained Template (show)
```
2) For PR of the same branch to master
```
[JTE] Obtained Pipeline Configuration File (show)
[JTE] Pipeline Configuration Modifications (show)
[JTE] Loading Library artifactory (show)
[JTE] Loading Library branch (show)
[JTE] Loading Library jenkins (show)
[JTE] Loading Library scm (show)
[JTE] Obtained Template (show)
```
```


### Steps to Reproduce

1) Install Bitbucket plugin 1.1.29
2) create pipeline - organization folder
3) make feature branch and PR

**Comment by e88z4** [comment]
I can also confirm this bug still exist in JTE 2.3.

**Comment by cokieffebah** [comment]
yeah. There are known issues around grabbing the configuration info in PRs in Bitbucket.

**Comment by kamorozov** [comment]
> yeah. There are known issues around grabbing the configuration info in PRs in Bitbucket.

So this is problem of BB plugin or JTE?

**Comment by steven-terrana** [comment]
I believe it's actually an issue with BitBucket itself. 

[BitBucket does not create a ref for pull requests](https://jira.atlassian.com/browse/BCLOUD-5814). 

This makes it so that the [BitBucket plugin(s) don't work as expected ](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java#L102-L104) with the Jenkins SCM API.

Which makes it so that on PR runs, JTE isn't able to fetch the `pipeline_config.groovy` file from the remote repository.
