### ISSUE TITLE
Error Loading Libraries

### ISSUE THREAD

**Issue by aleckeller** [jenkinsci/templating-engine-plugin#30]
Received the following error for all builds using JTE yesterday when it was loading in libraries:
[JTE] hudson.plugins.git.GitException: Command "git config remote.origin.url https://github.com/boozallen/sdp-libraries.git" returned status code 255: 
[JTE] stdout:
[JTE] stderr: error: could not lock config file .git/config: File exists

This error resulted in build failures for all of our jobs. 

Was able to fix the issue by going to $JENKINS_HOME/caches and running the command: 
"find . -type f -name "config.lock""
to find the location of the config.lock file. After finding where the file was, I removed it and this fixed the builds.

**Comment by steven-terrana** [comment]
This is likely a bug in the git-plugin's caching mechanism as all we JTE does is consume the API  provided by this plugin. 

i have been unable to reproduce this problem.  Do you have steps to reproduce?

**Comment by Quaiks** [comment]
Hello!!

When the clone of the library fails, because of reasons, the lock file is not deleted. The problem is that the cache folder is reused for every build so we have to delete manually those lock files.

How is the cache path decided? Is it possible to use a different one for every build?

Regards!

**Comment by vincent-r-kennedy** [comment]
Hi @steven-terrana   just to report we are having the same issue.

The root cause might be due to the git-plugin, but because it seems that JTE seems to us a shared cache for all the pipelines, if issue occurs then all the pipelines break at the same time.
Further more, if we delete the pipelines and try to recreate, the issue is still there as the cache seems to be 'above' the pipeline level. 

This is a complete nightmare as in our org, we do not have global jenkins admin rights and so can do nothing to fix the issue. 

I am wondering if JTE might be able to blow use a cache per pipeline (that would be deleted if the pipeline itself had to be rebuilt)?

**Comment by cokieffebah** [comment]
@vincent-r-kennedy @nayanbhana, I suspect the issue is either on the Git usage for your job repository or for your JTE configuration or library sources (under ${jenkins_host}/configure or in one of your tiers). have you tried adjusting the advanced options for either of the git sources?
<img width="1792" alt="Screen Shot 2021-01-29 at 9 28 27 AM" src="https://user-images.githubusercontent.com/23703182/106287195-7f53d300-6214-11eb-8b9a-ecda4d79c33b.png">

**Comment by vincent-r-kennedy** [comment]
@cokieffebah I had not thought of that mate - that seems like a very good idea!
I have set it up and will see how it goes. 
Many thanks for taking the time to respond!
