### ISSUE TITLE
[Bug]: short_name property isn't set on application environment

### ISSUE THREAD

**Issue by asknet** [jenkinsci/templating-engine-plugin#306]
### Jenkins Version

2.332.1

### JTE Version

2.5.2

### Bug Description

In template file, if I access pipelineConfig.application_environments["$appname"] then short_name property isn't set, whereas if I refer environment name directly then short_name property is set. Not sure why there is a difference

### Steps to Reproduce

In template file, if I access pipelineConfig.application_environments["$appname"] then short_name property isn't set, whereas if I refer environment name directly then short_name property is set. Not sure why there is a difference

**Comment by steven-terrana** [comment]
hey @asknet, 

The `pipelineConfig` variable represents the Aggregated Pipeline Configuration - which means that it's only going to contain the values set via the Pipeline Configuration. 

the `short_name` and `long_name` properties on Application Environments are on the _objects themselves_.

So, I would recommend using the Primitive Namespace variable (`jte`) variable instead of the Aggregated Pipeline Config (`pipelineConfig)` variable. 

Switching to the following will resolve your issue:
> `jte.application_environments["$appname").short_name`
