### ISSUE TITLE
[feature]: cross-library resource fetching

### ISSUE THREAD

**Issue by insummersnow** [jenkinsci/templating-engine-plugin#322]
### Feature Description

HI,
It is a company that actively utilizes JTE.

Thank you for developing this awesome plug-in.

I think I will register issues often from now on, so please take good care of me.

**Is there any way to share resources between libraries? Or is there no way to apply resources globally?**

**Comment by steven-terrana-bah** [comment]
hi @insummersnow - 

Library resources were intentionally built to not be able to directly access each other's resources to help guide users towards a best practice that libraries are, as much as possible, self-contained and self-sufficient. 

**[The `resource()` method is defined here](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/java/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperScript.java#L185-L208)**.

## Work-Around 

Because the method linked above is `public` (_perhaps it shouldn't be 😅_), you can access resources from other libraries by invoking that method on the step object that's created. 

for example, take the following library `example`:
```
example/
  resources/
    test.txt
  steps/
    test.groovy
```

JTE creates an object named `test` and injects it into your script context so that the `test` step can be executed from pipeline templates or other library steps. 

If you wanted to read the contents of `test.txt` from outside the `test` step.. you could call: `test.resource('test.txt')` and it would return what's expected.

**Comment by steven-terrana** [comment]
hi @insummersnow - 

Library resources were intentionally built to not be able to directly access each other's resources to help guide users towards a best practice that libraries are, as much as possible, self-contained and self-sufficient. 

**[The `resource()` method is defined here](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/java/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperScript.java#L185-L208)**.

## Work-Around 

Because the method linked above is `public` (_perhaps it shouldn't be 😅_), you can access resources from other libraries by invoking that method on the step object that's created. 

for example, take the following library `example`:
```
example/
  resources/
    test.txt
  steps/
    test.groovy
```

JTE creates an object named `test` and injects it into your script context so that the `test` step can be executed from pipeline templates or other library steps. 

If you wanted to read the contents of `test.txt` from outside the `test` step.. you could call: `test.resource('test.txt')` and it would return what's expected.

**Comment by steven-terrana** [comment]
Closing given the work around / solution described above.
