### ISSUE TITLE
Add support for Library Resources

### ISSUE THREAD

**Issue by nilave** [jenkinsci/templating-engine-plugin#46]
Hi , This template engine looks pretty neat and I'm trying to implement this in our organization. 

Wondering , whether there is any similar way to organize the supporting shell scripts used by groovy as they tend to become large in number and hard to organize.

Eg abc.groovy calls shells a1.sh , b1.sh for completing its tasks. we usually keep the a1.sh and b1.sh in scripts folder in git repo. Any way of organizing the shell scripts  as well along with this engine?

**Comment by steven-terrana** [comment]
hmm we could look into supporting the ``resources`` directory that regular jenkins shared libraries have.

**Comment by Vince-Cercury** [comment]
Hi. One of our team has written all their steps in make files. So that Jenkins is just the orchestration layer and they can switch to another tool easily. While I haven't used this approach myself, I totally understand why they would do this and the benefits (although there is some cons such as not leveraging built-in steps)

Not being able to call a bash script is preventing them from moving to JTE as they would lose the pattern and have to rewrite everything in groovy. (or have long groovy calls to inline bash which is not clean)

**Comment by steven-terrana** [comment]
Looks like i hadn't added the appropriate label - but this feature is on the short-list for implementation. 

actively working on the 2.0 release (no timeline for release just yet) and this feature will be included.

**Comment by Gl4di4torRr** [comment]
+1

**Comment by steven-terrana** [comment]
This functionality has been implemented and will be part of the 2.0 release
