### ISSUE TITLE
Where do I define "custom variables"?

### ISSUE THREAD

**Issue by straurob** [jenkinsci/templating-engine-plugin#59]
I'm trying to implement a proof-of-concept for my project using the [Jenkins Template Engine][1]. However it seems as if I'm still missing something in the concept. Please find the following files as an example:

**General pipeline_config.groovy**

    libraries {
        merge = true // allow individual apps to contribute additional libraries
        docker
    }

**Docker library step: build_docker.groovy**

    void call() {
        println "Building and publishing Docker image ${DOCKER_REGISTRY}/${APP_NAME}"
    }

**Application-specific pipeline_config.groovy**

    libraries {
        gradle
    }

As you might see I'd like to use the variables `$DOCKER_REGISTRY` and `$APP_NAME`:

1. `$DOCKER_REGISTRY` shall be a "global" variable which is valid for all pipeline library steps.
2. `$APP_NAME` shall be a variable specific for the application.

My problem is: Where do I define these variables so that they are usable in the required scope?

I already tried the following but this doesn't work:

    libraries {
        gradle
        docker {
          APP_NAME = "my-app"
        }
    }

  [1]: https://jenkinsci.github.io/templating-engine-plugin/

**Comment by steven-terrana** [comment]
hey @straurob, 

let's start with the basics for JTE. 

When you define a variable in the library spec, it gets placed on an autowired ``config`` variable that's accessible within your steps. 

so you could say:

~~~
libraries{
  docker{
    DOCKER_REGISTRY = "registry"
    APP_NAME = "app" 
  }
}
~~~

and then in your step you could say: 

~~~
println "Building and publishing Docker image ${config.DOCKER_REGISTRY}/${config.APP_NAME}" 
~~~


if you need a variable accessible to both libraries, i'd probably recommend defining it twice so that your libraries are self contained in their functionality

but you could also do 

~~~
APP_NAME = "app" 

libraries{
  gradle
  docker{
    DOCKER_REGISTRY = "registry" 
  }
}
~~~

and then leverage the global ``pipelineConfig`` variable to access ``APP_NAME`` via ``pipelineConfig.APP_NAME`` 

and finally, there's the Keyword primitive 

you could define variables via 

~~~
keywords{
  APP_NAME = "app" 
}
~~~

and then access it via plain old ``println APP_NAME``

hope this helps!

**Comment by straurob** [comment]
Thanks @steven-terrana , this helps and answers my question :-)
