### ISSUE TITLE
How to handle conflicting libraries

### ISSUE THREAD

**Issue by DuckieHo** [jenkinsci/templating-engine-plugin#62]
Would you have an example or guidance on a case where the repository has a stage with parallel steps with the same library functions?

**Example**
A repo contains both C++ and Java source code.  For the build stage, I want to call both a **gradle** build and **make** build in parallel.

**Questions**
1) How do would do you run steps in parallel under JTE?
2) How would JTE resolve the possible library conflict with _../gradle/build.groovy_ and _../make/build.groovy_?

**Comment by steven-terrana** [comment]
Interesting question. 

I'm going to use this issue to talk about a few different options, so sorry if i ramble a bit. 

## General Advice 
My general advice for this situation would probably be to create two different pipelines for the same repository.  One responsible for the C++ code and one for the Java code.  This way - you can leverage two different pipeline configurations for the same source code repository. 

## Future Feature Opportunities for JTE

That advice can usually get folks through most common situations where these step collisions happen but there's an opportunity to enhance JTE further to provide more graceful implementations through a less-strict initialization process.

I could see a scenario where we allow JTE to be less strict when loading the pipeline's to-be runtime environment based upon the aggregated configuration.  

This less-strict mode would be configurable from the pipeline configuration file (_and named better.._) and when turned on, would not automatically fail the pipeline when conflicts in step name occur. 

I see two possible solutions here, but i'm open to others. 

### Step Namespacing

Instead of failure, we could **namespace** steps onto a `jte` variable that has a field for each loaded library.  So in this particular example, imagine being able to do: 

```
jte.cpp.build()
jte.gradle.build() 
```

### Step Aliasing

instead of namespacing everything to allow for a less strict initialization, we could also create *step aliasing* so that from your pipeline configuration file you can _change_ the name of a step at runtime. 

I'm picturing something like..

**example.groovy from example library**
~~~
@StepAlias({ return config.step_alias.example })
void call(){
  println "example" 
}
~~~

and then a pipeline configuration of: 
~~~
libraries{
  example{
    step_aliases{
      example = "build" 
    }
  }
}
~~~

so in this case... the `example` step would get **loaded** as a step named _build_

--- 

Thoughts?  I'm going to share this issue around and see what the community ideas are for solving it.

**Comment by DuckieHo** [comment]
Does JTE support parallel pipeline stages?


The space namespacing approach _smells_ like a more straightforward approach.  Default to lowest common denominator.  If there is a collision, JTE already throws an error.  Users have an outlet now to provide a more explicit namespace (as needed).

Aliases may introduce yet another abstraction layer which needs to be traced.

**Comment by steven-terrana** [comment]
To answer your question, yes JTE supports parallel pipeline stages. 

Pipeline Templates in JTE get executed just like regular Jenkinsfiles so you can do 

```
parallel "step1": { step1() },
             "step2": { step2() }
```

syntax just like you would in a Jenkins scripted pipeline.
