### ISSUE TITLE
JTE invokes a node block during initialization that cannot be passed a label

### ISSUE THREAD

**Issue by maxfouquet** [jenkinsci/templating-engine-plugin#63]
Hi,

I search for a way to force node label in pipeline template.

I tried this but it doesn't work :

```
properties([
    parameters([
        ...
    ])
])

node('master'){
     stage('Stage 1'){
          fonction1()
     }
     stage('Stage 1'){
          fonction2()
     }
}
```

Did you implement an other way to do this ?

Thanks

**Comment by steven-terrana** [comment]
hey @maxfouquet. 

Does it specifically not work during JTE initialization? 

There is a known opportunity for improvement in JTE where, during initialization, we invoke a `node` step without giving users the opportunity to pass a label. 

Right now, the best workaround for this would be to load a library that has a custom implementation of the node step, so that you can configure the label to use from your pipeline configuration file. 

Here is an example of what a custom node step implementation contributed by a library might look like: 

https://github.com/steven-terrana/jte-custom-node-step/blob/master/utility/node.groovy
