### ISSUE TITLE
Would like to know if it is support the Jenkins Kubernetes plugin

### ISSUE THREAD

**Issue by XiaoduLiu** [jenkinsci/templating-engine-plugin#67]
We have deployed the Jenkins in Kubernetes and use the kubernetes to lunch the agent pod dynamically.  Here is our steps:

/libraries/maven/build.groovy

void call(){
  def label = "agent-${UUID.randomUUID().toString()}"
  podTemplate(
    cloud: 'pas-development',
    serviceAccount: 'jenkins',
    namespace: 'devops-jenkins',
    containers: [
      containerTemplate(name: 'jnlp', image: "${env.TOOL_AGENT}", args: '${computer.jnlpmac} ${computer.name}')
  ]){
      node(label) {
        stage("Maven: Build"){
          println "build from the maven library"
        }
      }
  }
}

The pipeline is hanging and the agent pod never lunched.

I would like to know if it support the kubernetes plugin.  If so, how we can do it.  Thanks

Louie Liu

**Comment by steven-terrana** [comment]
Hello, the issue was caused by the fact that JTE used to make calls to `node` blocks during initialization, before executing the template, without passing a node label. 

This often resulted in JTE hanging for users that were leveraging Cloud plugins or needed agent-specific selection for all node blocks. 

The PR goes into more detail.

This was removed in [JTE 1.7](https://github.com/jenkinsci/templating-engine-plugin/releases/tag/1.7)
