### ISSUE TITLE
Removing the default checkout ability now clashes with gitlab-branch-source-plugin

### ISSUE THREAD

**Issue by Opa-** [jenkinsci/templating-engine-plugin#74]
Hello,

I'm using both `templating-engine-plugin` and `gitlab-branch-source-plugin`.
In `gitlab-branch-source-plugin`, there's a post-hook on the checkout to send a notification to GitLab (https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/a894e782d62cea3ce53a3374d23b38d2783a1ca3/src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java#L373) which allows to consider the build as RUNNING is GitLab-CI if `currentBuild.result` is `null` in Jenkins (https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/a894e782d62cea3ce53a3374d23b38d2783a1ca3/src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java#L209)

Since the version 1.7 of `templating-engine-plugin`, the ability to have JTE performing the checkout have been removed and I do have to do it manually.
This is fine, but, just below where the checkout happened before, there's a manual assignation
https://github.com/jenkinsci/templating-engine-plugin/blob/5959425c7dfaef250711a3f20bad75878c52a0b9/src/main/resources/org/boozallen/plugins/jte/TemplateEntryPoint.groovy#L36
Because of that, when the post-hook on the SCM checkout is performed by `gitlab-branch-source-plugin`, the result is no longer `null` but `SUCCESS` resulting in the GitLab-CI pipeline displaying as success while the unit testing did not even started yet.

Maybe I'm missing a use case here but is there a real need to copy the `currentBuild.result` into `context.status` while we can access it with `currentBuild.result` in our pipelines when needed ?
Would it be possible to set it to `null` at start ?

**Comment by steven-terrana** [comment]
i really appreciate the in-depth issue here. 

I think that is a valid concern and you're right - people can just access `currentBuild` in their steps if they need to. 

If you would be willing to contribute this fix, i'd be happy to merge and will outline where the updates would have to happen. 

otherwise i'll get to this as soon as i can. 

Update context passed to hooks: 

1. [TemplateEntryPoint](https://github.com/jenkinsci/templating-engine-plugin/blob/master/src/main/resources/org/boozallen/plugins/jte/TemplateEntryPoint.groovy#L35-L41)
2. [Before and after step invocation](https://github.com/jenkinsci/templating-engine-plugin/blob/master/src/main/resources/org/boozallen/plugins/jte/binding/injectors/StepWrapper.groovy#L77-L99)
3. [The Docs](https://github.com/jenkinsci/templating-engine-plugin/blob/master/docs/modules/library-development/pages/lifecycle_hooks.adoc)
4. Unit tests maybe? 

there _might_ be others, but off the top of my head those are all the places :). 

so again - happy to review and help with a PR if you have the time! otherwise i'll get to this when i can

**Comment by steven-terrana** [comment]
not sure if this is an enhancement or a bug 🤔

**Comment by Opa-** [comment]
Thanks for the links, I'll find time to make the fix ASAP. Hopefully this week 😀

I'd say this is a bug introduced by 1.7 since it kinda breaks something that was working previously, What do you think ?

**Comment by steven-terrana** [comment]
yeah, agree. 

i found time to do it today! i'll be releasing shortly

**Comment by steven-terrana** [comment]
https://github.com/jenkinsci/templating-engine-plugin/pull/77

**Comment by Opa-** [comment]
Thank you for your responsiveness 🙂
