### ISSUE TITLE
Set custom path for pipeline configuration file in the source code repository

### ISSUE THREAD

**Issue by jemerald** [jenkinsci/templating-engine-plugin#99]
### Feature Request

Our repository contains application code (.NET) as well as documentation (markdown format published with vuepress)

the 2 parts are built completely differently (one with dotnet library, the other with nodejs library), and has different deployment lifecycles (application deployed through the usual dev/test/prod, whereas documentation is published to a single site)

We'd like to have 2 separate Jenkins multibranch pipelines to build the 2 parts. But currently there is no way to specify the config file as it is hard-coded to `pipeline_config.groovy`.

It would be great if the plugin allows custom config file path to facilitate this, similar to how the Jenkinsfile build allows specifying the path for Jenkinsfile.

**Comment by steven-terrana** [comment]
good idea, definitely something we can look into after v2.0 is finished!

in the meantime, a work around to accomplish this could be creating a subdirectory with the pipeline_config.groovy file for each use case. 

`.jte/nodejs/pipeline_config.groovy`
`.jte/dotnet/pipeline_config.groovy`

and then making the _repository itself_ a governance tier with the configuration base directory being `.jte/nodejs` and `.jte/dotnet`, respectively.

**Comment by jemerald** [comment]
Interesting work around, I'll give that a try, thanks @steven-terrana

**Comment by jemerald** [comment]
The work around worked OK, apart from the more complex setup, the drawback is that the subdirectory config can only point to a single branch, unlike the main `pipeline_config.groovy` is loaded from the branch that's getting built.

Looking forward for the support for custom config filename.

**Comment by steven-terrana** [comment]
if anyone has the bandwidth to pick this up - the work would be update the [TemplateBranchProjectFactory](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory.groovy) and the [TemplateMultiBranchProjectFactory](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/job/TemplateMultiBranchProjectFactory.groovy) to store a `String` for the path to find the repository's Pipeline Configuration file. 

Then, inside [`getJobPipelineConfiguration`](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/init/PipelineDecorator.groovy#L90) you'd have to check if the job type is of [MultibranchTemplateFlowDefinition](https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/job/MultibranchTemplateFlowDefinition.groovy) and ask for that path explicitly instead of just assuming it was `pipeline_config.groovy`
